/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.cmis4j.core.impl;

import java.util.logging.Logger;

import org.oasis_open.docs.ns.cmis.ws._200908.ACLServicePort;
import org.oasis_open.docs.ns.cmis.ws._200908.CmisException;

/**
 * This class was generated by Apache CXF 2.7.7 2014-02-19T05:53:39.546-06:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(serviceName = "ACLService", portName = "ACLServicePort", targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/", endpointInterface = "org.oasis_open.docs.ns.cmis.ws._200908.ACLServicePort")
public class ACLServicePortImpl implements ACLServicePort {

	private static final Logger LOG = Logger.getLogger(ACLServicePortImpl.class
			.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.ACLServicePort#applyACL(java.lang
	 * .String repositoryId ,)java.lang.String objectId
	 * ,)org.oasis_open.docs.ns.cmis.core._200908.CmisAccessControlListType
	 * addACEs
	 * ,)org.oasis_open.docs.ns.cmis.core._200908.CmisAccessControlListType
	 * removeACEs ,)org.oasis_open.docs.ns.cmis.core._200908.EnumACLPropagation
	 * aclPropagation
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public org.oasis_open.docs.ns.cmis.messaging._200908.CmisACLType applyACL(
			java.lang.String repositoryId,
			java.lang.String objectId,
			org.oasis_open.docs.ns.cmis.core._200908.CmisAccessControlListType addACEs,
			org.oasis_open.docs.ns.cmis.core._200908.CmisAccessControlListType removeACEs,
			org.oasis_open.docs.ns.cmis.core._200908.EnumACLPropagation aclPropagation,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation applyACL");
		System.out.println(repositoryId);
		System.out.println(objectId);
		System.out.println(addACEs);
		System.out.println(removeACEs);
		System.out.println(aclPropagation);
		System.out.println(extension);
		try {
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisACLType _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.ACLServicePort#getACL(java.lang
	 * .String repositoryId ,)java.lang.String objectId ,)java.lang.Boolean
	 * onlyBasicPermissions
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public org.oasis_open.docs.ns.cmis.messaging._200908.CmisACLType getACL(
			java.lang.String repositoryId,
			java.lang.String objectId,
			java.lang.Boolean onlyBasicPermissions,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation getACL");
		System.out.println(repositoryId);
		System.out.println(objectId);
		System.out.println(onlyBasicPermissions);
		System.out.println(extension);
		try {
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisACLType _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

}
