/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.cmis4j.core.impl;

import java.util.logging.Logger;

import org.oasis_open.docs.ns.cmis.ws._200908.CmisException;
import org.oasis_open.docs.ns.cmis.ws._200908.DiscoveryServicePort;

/**
 * This class was generated by Apache CXF 2.7.7 2014-02-19T05:53:39.578-06:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(serviceName = "DiscoveryService", portName = "DiscoveryServicePort", targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/", endpointInterface = "org.oasis_open.docs.ns.cmis.ws._200908.DiscoveryServicePort")
public class DiscoveryServicePortImpl implements DiscoveryServicePort {

	private static final Logger LOG = Logger
			.getLogger(DiscoveryServicePortImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.DiscoveryServicePort#query(org
	 * .oasis_open.docs.ns.cmis.messaging._200908.Query parameters )*
	 */
	@Override
	public org.oasis_open.docs.ns.cmis.messaging._200908.QueryResponse query(
			org.oasis_open.docs.ns.cmis.messaging._200908.Query parameters)
			throws CmisException {
		LOG.info("Executing operation query");
		System.out.println(parameters);
		try {
			org.oasis_open.docs.ns.cmis.messaging._200908.QueryResponse _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.DiscoveryServicePort#getContentChanges
	 * (java.lang.String repositoryId ,)java.lang.String changeLogToken
	 * ,)java.lang.Boolean includeProperties ,)java.lang.String filter
	 * ,)java.lang.Boolean includePolicyIds ,)java.lang.Boolean includeACL
	 * ,)java.math.BigInteger maxItems
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectListType
	 * objects )*
	 */
	@Override
	public void getContentChanges(
			java.lang.String repositoryId,
			javax.xml.ws.Holder<java.lang.String> changeLogToken,
			java.lang.Boolean includeProperties,
			java.lang.String filter,
			java.lang.Boolean includePolicyIds,
			java.lang.Boolean includeACL,
			java.math.BigInteger maxItems,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension,
			javax.xml.ws.Holder<org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectListType> objects)
			throws CmisException {
		LOG.info("Executing operation getContentChanges");
		System.out.println(repositoryId);
		System.out.println(changeLogToken.value);
		System.out.println(includeProperties);
		System.out.println(filter);
		System.out.println(includePolicyIds);
		System.out.println(includeACL);
		System.out.println(maxItems);
		System.out.println(extension);
		try {
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectListType objectsValue = null;
			objects.value = objectsValue;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

}
