/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.cmis4j.core.impl;

import java.util.logging.Logger;

import org.oasis_open.docs.ns.cmis.ws._200908.CmisException;
import org.oasis_open.docs.ns.cmis.ws._200908.MultiFilingServicePort;

/**
 * This class was generated by Apache CXF 2.7.7 2014-02-19T05:53:39.578-06:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(serviceName = "MultiFilingService", portName = "MultiFilingServicePort", targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/", endpointInterface = "org.oasis_open.docs.ns.cmis.ws._200908.MultiFilingServicePort")
public class MultiFilingServicePortImpl implements MultiFilingServicePort {

	private static final Logger LOG = Logger
			.getLogger(MultiFilingServicePortImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.oasis_open.docs.ns.cmis.ws._200908.MultiFilingServicePort#
	 * removeObjectFromFolder(java.lang.String repositoryId ,)java.lang.String
	 * objectId ,)java.lang.String folderId
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public void removeObjectFromFolder(
			java.lang.String repositoryId,
			java.lang.String objectId,
			java.lang.String folderId,
			javax.xml.ws.Holder<org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType> extension)
			throws CmisException {
		LOG.info("Executing operation removeObjectFromFolder");
		System.out.println(repositoryId);
		System.out.println(objectId);
		System.out.println(folderId);
		System.out.println(extension.value);
		try {
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.oasis_open.docs.ns.cmis.ws._200908.MultiFilingServicePort#
	 * addObjectToFolder(java.lang.String repositoryId ,)java.lang.String
	 * objectId ,)java.lang.String folderId ,)java.lang.Boolean allVersions
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public void addObjectToFolder(
			java.lang.String repositoryId,
			java.lang.String objectId,
			java.lang.String folderId,
			java.lang.Boolean allVersions,
			javax.xml.ws.Holder<org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType> extension)
			throws CmisException {
		LOG.info("Executing operation addObjectToFolder");
		System.out.println(repositoryId);
		System.out.println(objectId);
		System.out.println(folderId);
		System.out.println(allVersions);
		System.out.println(extension.value);
		try {
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

}
