/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.cmis4j.core.impl;

import java.util.logging.Logger;

import org.oasis_open.docs.ns.cmis.ws._200908.CmisException;
import org.oasis_open.docs.ns.cmis.ws._200908.NavigationServicePort;

/**
 * This class was generated by Apache CXF 2.7.7 2014-02-19T05:53:39.484-06:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(serviceName = "NavigationService", portName = "NavigationServicePort", targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/", endpointInterface = "org.oasis_open.docs.ns.cmis.ws._200908.NavigationServicePort")
public class NavigationServicePortImpl implements NavigationServicePort {

	private static final Logger LOG = Logger
			.getLogger(NavigationServicePortImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.oasis_open.docs.ns.cmis.ws._200908.NavigationServicePort#
	 * getCheckedOutDocs(java.lang.String repositoryId ,)java.lang.String
	 * folderId ,)java.lang.String filter ,)java.lang.String orderBy
	 * ,)java.lang.Boolean includeAllowableActions
	 * ,)org.oasis_open.docs.ns.cmis.core._200908.EnumIncludeRelationships
	 * includeRelationships ,)java.lang.String renditionFilter
	 * ,)java.math.BigInteger maxItems ,)java.math.BigInteger skipCount
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectListType getCheckedOutDocs(
			java.lang.String repositoryId,
			java.lang.String folderId,
			java.lang.String filter,
			java.lang.String orderBy,
			java.lang.Boolean includeAllowableActions,
			org.oasis_open.docs.ns.cmis.core._200908.EnumIncludeRelationships includeRelationships,
			java.lang.String renditionFilter,
			java.math.BigInteger maxItems,
			java.math.BigInteger skipCount,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation getCheckedOutDocs");
		System.out.println(repositoryId);
		System.out.println(folderId);
		System.out.println(filter);
		System.out.println(orderBy);
		System.out.println(includeAllowableActions);
		System.out.println(includeRelationships);
		System.out.println(renditionFilter);
		System.out.println(maxItems);
		System.out.println(skipCount);
		System.out.println(extension);
		try {
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectListType _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.NavigationServicePort#getObjectParents
	 * (java.lang.String repositoryId ,)java.lang.String objectId
	 * ,)java.lang.String filter ,)java.lang.Boolean includeAllowableActions
	 * ,)org.oasis_open.docs.ns.cmis.core._200908.EnumIncludeRelationships
	 * includeRelationships ,)java.lang.String renditionFilter
	 * ,)java.lang.Boolean includeRelativePathSegment
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public java.util.List<org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectParentsType> getObjectParents(
			java.lang.String repositoryId,
			java.lang.String objectId,
			java.lang.String filter,
			java.lang.Boolean includeAllowableActions,
			org.oasis_open.docs.ns.cmis.core._200908.EnumIncludeRelationships includeRelationships,
			java.lang.String renditionFilter,
			java.lang.Boolean includeRelativePathSegment,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation getObjectParents");
		System.out.println(repositoryId);
		System.out.println(objectId);
		System.out.println(filter);
		System.out.println(includeAllowableActions);
		System.out.println(includeRelationships);
		System.out.println(renditionFilter);
		System.out.println(includeRelativePathSegment);
		System.out.println(extension);
		try {
			java.util.List<org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectParentsType> _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.NavigationServicePort#getDescendants
	 * (java.lang.String repositoryId ,)java.lang.String folderId
	 * ,)java.math.BigInteger depth ,)java.lang.String filter
	 * ,)java.lang.Boolean includeAllowableActions
	 * ,)org.oasis_open.docs.ns.cmis.core._200908.EnumIncludeRelationships
	 * includeRelationships ,)java.lang.String renditionFilter
	 * ,)java.lang.Boolean includePathSegment
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public java.util.List<org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectInFolderContainerType> getDescendants(
			java.lang.String repositoryId,
			java.lang.String folderId,
			java.math.BigInteger depth,
			java.lang.String filter,
			java.lang.Boolean includeAllowableActions,
			org.oasis_open.docs.ns.cmis.core._200908.EnumIncludeRelationships includeRelationships,
			java.lang.String renditionFilter,
			java.lang.Boolean includePathSegment,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation getDescendants");
		System.out.println(repositoryId);
		System.out.println(folderId);
		System.out.println(depth);
		System.out.println(filter);
		System.out.println(includeAllowableActions);
		System.out.println(includeRelationships);
		System.out.println(renditionFilter);
		System.out.println(includePathSegment);
		System.out.println(extension);
		try {
			java.util.List<org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectInFolderContainerType> _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.NavigationServicePort#getChildren
	 * (java.lang.String repositoryId ,)java.lang.String folderId
	 * ,)java.lang.String filter ,)java.lang.String orderBy ,)java.lang.Boolean
	 * includeAllowableActions
	 * ,)org.oasis_open.docs.ns.cmis.core._200908.EnumIncludeRelationships
	 * includeRelationships ,)java.lang.String renditionFilter
	 * ,)java.lang.Boolean includePathSegment ,)java.math.BigInteger maxItems
	 * ,)java.math.BigInteger skipCount
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectInFolderListType getChildren(
			java.lang.String repositoryId,
			java.lang.String folderId,
			java.lang.String filter,
			java.lang.String orderBy,
			java.lang.Boolean includeAllowableActions,
			org.oasis_open.docs.ns.cmis.core._200908.EnumIncludeRelationships includeRelationships,
			java.lang.String renditionFilter,
			java.lang.Boolean includePathSegment,
			java.math.BigInteger maxItems,
			java.math.BigInteger skipCount,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation getChildren");
		System.out.println(repositoryId);
		System.out.println(folderId);
		System.out.println(filter);
		System.out.println(orderBy);
		System.out.println(includeAllowableActions);
		System.out.println(includeRelationships);
		System.out.println(renditionFilter);
		System.out.println(includePathSegment);
		System.out.println(maxItems);
		System.out.println(skipCount);
		System.out.println(extension);
		try {
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectInFolderListType _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.NavigationServicePort#getFolderTree
	 * (java.lang.String repositoryId ,)java.lang.String folderId
	 * ,)java.math.BigInteger depth ,)java.lang.String filter
	 * ,)java.lang.Boolean includeAllowableActions
	 * ,)org.oasis_open.docs.ns.cmis.core._200908.EnumIncludeRelationships
	 * includeRelationships ,)java.lang.String renditionFilter
	 * ,)java.lang.Boolean includePathSegment
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public java.util.List<org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectInFolderContainerType> getFolderTree(
			java.lang.String repositoryId,
			java.lang.String folderId,
			java.math.BigInteger depth,
			java.lang.String filter,
			java.lang.Boolean includeAllowableActions,
			org.oasis_open.docs.ns.cmis.core._200908.EnumIncludeRelationships includeRelationships,
			java.lang.String renditionFilter,
			java.lang.Boolean includePathSegment,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation getFolderTree");
		System.out.println(repositoryId);
		System.out.println(folderId);
		System.out.println(depth);
		System.out.println(filter);
		System.out.println(includeAllowableActions);
		System.out.println(includeRelationships);
		System.out.println(renditionFilter);
		System.out.println(includePathSegment);
		System.out.println(extension);
		try {
			java.util.List<org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectInFolderContainerType> _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.NavigationServicePort#getFolderParent
	 * (java.lang.String repositoryId ,)java.lang.String folderId
	 * ,)java.lang.String filter
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public org.oasis_open.docs.ns.cmis.core._200908.CmisObjectType getFolderParent(
			java.lang.String repositoryId,
			java.lang.String folderId,
			java.lang.String filter,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation getFolderParent");
		System.out.println(repositoryId);
		System.out.println(folderId);
		System.out.println(filter);
		System.out.println(extension);
		try {
			org.oasis_open.docs.ns.cmis.core._200908.CmisObjectType _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

}
