/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.cmis4j.core.impl;

import java.util.logging.Logger;

import org.oasis_open.docs.ns.cmis.ws._200908.CmisException;
import org.oasis_open.docs.ns.cmis.ws._200908.RelationshipServicePort;

/**
 * This class was generated by Apache CXF 2.7.7 2014-02-19T05:53:39.578-06:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(serviceName = "RelationshipService", portName = "RelationshipServicePort", targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/", endpointInterface = "org.oasis_open.docs.ns.cmis.ws._200908.RelationshipServicePort")
public class RelationshipServicePortImpl implements RelationshipServicePort {

	private static final Logger LOG = Logger
			.getLogger(RelationshipServicePortImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.oasis_open.docs.ns.cmis.ws._200908.RelationshipServicePort#
	 * getObjectRelationships(java.lang.String repositoryId ,)java.lang.String
	 * objectId ,)java.lang.Boolean includeSubRelationshipTypes
	 * ,)org.oasis_open.docs.ns.cmis.core._200908.EnumRelationshipDirection
	 * relationshipDirection ,)java.lang.String typeId ,)java.lang.String filter
	 * ,)java.lang.Boolean includeAllowableActions ,)java.math.BigInteger
	 * maxItems ,)java.math.BigInteger skipCount
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectListType getObjectRelationships(
			java.lang.String repositoryId,
			java.lang.String objectId,
			java.lang.Boolean includeSubRelationshipTypes,
			org.oasis_open.docs.ns.cmis.core._200908.EnumRelationshipDirection relationshipDirection,
			java.lang.String typeId,
			java.lang.String filter,
			java.lang.Boolean includeAllowableActions,
			java.math.BigInteger maxItems,
			java.math.BigInteger skipCount,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation getObjectRelationships");
		System.out.println(repositoryId);
		System.out.println(objectId);
		System.out.println(includeSubRelationshipTypes);
		System.out.println(relationshipDirection);
		System.out.println(typeId);
		System.out.println(filter);
		System.out.println(includeAllowableActions);
		System.out.println(maxItems);
		System.out.println(skipCount);
		System.out.println(extension);
		try {
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectListType _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

}
