/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.cmis4j.core.impl;

import java.util.logging.Logger;

import org.oasis_open.docs.ns.cmis.ws._200908.CmisException;
import org.oasis_open.docs.ns.cmis.ws._200908.RepositoryServicePort;

/**
 * This class was generated by Apache CXF 2.7.7 2014-02-19T05:53:39.593-06:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(serviceName = "RepositoryService", portName = "RepositoryServicePort", targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/", endpointInterface = "org.oasis_open.docs.ns.cmis.ws._200908.RepositoryServicePort")
public class RepositoryServicePortImpl implements RepositoryServicePort {

	private static final Logger LOG = Logger
			.getLogger(RepositoryServicePortImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.RepositoryServicePort#getTypeChildren
	 * (java.lang.String repositoryId ,)java.lang.String typeId
	 * ,)java.lang.Boolean includePropertyDefinitions ,)java.math.BigInteger
	 * maxItems ,)java.math.BigInteger skipCount
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public org.oasis_open.docs.ns.cmis.messaging._200908.CmisTypeDefinitionListType getTypeChildren(
			java.lang.String repositoryId,
			java.lang.String typeId,
			java.lang.Boolean includePropertyDefinitions,
			java.math.BigInteger maxItems,
			java.math.BigInteger skipCount,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation getTypeChildren");
		System.out.println(repositoryId);
		System.out.println(typeId);
		System.out.println(includePropertyDefinitions);
		System.out.println(maxItems);
		System.out.println(skipCount);
		System.out.println(extension);
		try {
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisTypeDefinitionListType _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.oasis_open.docs.ns.cmis.ws._200908.RepositoryServicePort#
	 * getTypeDefinition(java.lang.String repositoryId ,)java.lang.String typeId
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public org.oasis_open.docs.ns.cmis.core._200908.CmisTypeDefinitionType getTypeDefinition(
			java.lang.String repositoryId,
			java.lang.String typeId,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation getTypeDefinition");
		System.out.println(repositoryId);
		System.out.println(typeId);
		System.out.println(extension);
		try {
			org.oasis_open.docs.ns.cmis.core._200908.CmisTypeDefinitionType _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.RepositoryServicePort#updateType
	 * (java.lang.String repositoryId
	 * ,)org.oasis_open.docs.ns.cmis.core._200908.CmisTypeDefinitionType type
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public void updateType(
			java.lang.String repositoryId,
			javax.xml.ws.Holder<org.oasis_open.docs.ns.cmis.core._200908.CmisTypeDefinitionType> type,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation updateType");
		System.out.println(repositoryId);
		System.out.println(type.value);
		System.out.println(extension);
		try {
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.oasis_open.docs.ns.cmis.ws._200908.RepositoryServicePort#
	 * getRepositoryInfo(java.lang.String repositoryId
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public org.oasis_open.docs.ns.cmis.core._200908.CmisRepositoryInfoType getRepositoryInfo(
			java.lang.String repositoryId,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation getRepositoryInfo");
		System.out.println(repositoryId);
		System.out.println(extension);
		try {
			org.oasis_open.docs.ns.cmis.core._200908.CmisRepositoryInfoType _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.RepositoryServicePort#deleteType
	 * (java.lang.String repositoryId ,)java.lang.String typeId
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public void deleteType(
			java.lang.String repositoryId,
			java.lang.String typeId,
			javax.xml.ws.Holder<org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType> extension)
			throws CmisException {
		LOG.info("Executing operation deleteType");
		System.out.println(repositoryId);
		System.out.println(typeId);
		System.out.println(extension.value);
		try {
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.oasis_open.docs.ns.cmis.ws._200908.RepositoryServicePort#
	 * getTypeDescendants(java.lang.String repositoryId ,)java.lang.String
	 * typeId ,)java.math.BigInteger depth ,)java.lang.Boolean
	 * includePropertyDefinitions
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public java.util.List<org.oasis_open.docs.ns.cmis.messaging._200908.CmisTypeContainer> getTypeDescendants(
			java.lang.String repositoryId,
			java.lang.String typeId,
			java.math.BigInteger depth,
			java.lang.Boolean includePropertyDefinitions,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation getTypeDescendants");
		System.out.println(repositoryId);
		System.out.println(typeId);
		System.out.println(depth);
		System.out.println(includePropertyDefinitions);
		System.out.println(extension);
		try {
			java.util.List<org.oasis_open.docs.ns.cmis.messaging._200908.CmisTypeContainer> _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.RepositoryServicePort#createType
	 * (java.lang.String repositoryId
	 * ,)org.oasis_open.docs.ns.cmis.core._200908.CmisTypeDefinitionType type
	 * ,)org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public void createType(
			java.lang.String repositoryId,
			javax.xml.ws.Holder<org.oasis_open.docs.ns.cmis.core._200908.CmisTypeDefinitionType> type,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation createType");
		System.out.println(repositoryId);
		System.out.println(type.value);
		System.out.println(extension);
		try {
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.oasis_open.docs.ns.cmis.ws._200908.RepositoryServicePort#getRepositories
	 * (org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType
	 * extension )*
	 */
	@Override
	public java.util.List<org.oasis_open.docs.ns.cmis.messaging._200908.CmisRepositoryEntryType> getRepositories(
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException {
		LOG.info("Executing operation getRepositories");
		System.out.println(extension);
		try {
			java.util.List<org.oasis_open.docs.ns.cmis.messaging._200908.CmisRepositoryEntryType> _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new CmisException("cmisException...");
	}

}
