package org.oasis_open.docs.ns.cmis.ws._200908;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7 2014-02-19T05:53:39.625-06:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/", name = "ACLServicePort")
@XmlSeeAlso({ org.oasis_open.docs.ns.cmis.core._200908.ObjectFactory.class,
		org.oasis_open.docs.ns.cmis.messaging._200908.ObjectFactory.class })
public interface ACLServicePort {

	@WebResult(name = "ACL", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
	@RequestWrapper(localName = "applyACL", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.ApplyACL")
	@WebMethod(action = "applyACL")
	@ResponseWrapper(localName = "applyACLResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.ApplyACLResponse")
	public org.oasis_open.docs.ns.cmis.messaging._200908.CmisACLType applyACL(
			@WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String repositoryId,
			@WebParam(name = "objectId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String objectId,
			@WebParam(name = "addACEs", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") org.oasis_open.docs.ns.cmis.core._200908.CmisAccessControlListType addACEs,
			@WebParam(name = "removeACEs", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") org.oasis_open.docs.ns.cmis.core._200908.CmisAccessControlListType removeACEs,
			@WebParam(name = "ACLPropagation", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") org.oasis_open.docs.ns.cmis.core._200908.EnumACLPropagation aclPropagation,
			@WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException;

	@WebResult(name = "ACL", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
	@RequestWrapper(localName = "getACL", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.GetACL")
	@WebMethod(action = "getACL")
	@ResponseWrapper(localName = "getACLResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.GetACLResponse")
	public org.oasis_open.docs.ns.cmis.messaging._200908.CmisACLType getACL(
			@WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String repositoryId,
			@WebParam(name = "objectId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String objectId,
			@WebParam(name = "onlyBasicPermissions", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.Boolean onlyBasicPermissions,
			@WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException;
}
