package org.oasis_open.docs.ns.cmis.ws._200908;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.7.7 2014-02-24T15:14:54.812-06:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "cmisFault", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
public class CmisException extends Exception {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3566916970133215637L;
	private org.oasis_open.docs.ns.cmis.messaging._200908.CmisFaultType cmisFault;

	public CmisException() {
		super();
	}

	public CmisException(String message) {
		super(message);
	}

	public CmisException(String message, Throwable cause) {
		super(message, cause);
	}

	public CmisException(
			String message,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisFaultType cmisFault) {
		super(message);
		this.cmisFault = cmisFault;
	}

	public CmisException(
			String message,
			org.oasis_open.docs.ns.cmis.messaging._200908.CmisFaultType cmisFault,
			Throwable cause) {
		super(message, cause);
		this.cmisFault = cmisFault;
	}

	public org.oasis_open.docs.ns.cmis.messaging._200908.CmisFaultType getFaultInfo() {
		return this.cmisFault;
	}
}
