package org.oasis_open.docs.ns.cmis.ws._200908;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7 2014-02-19T05:53:39.656-06:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/", name = "RepositoryServicePort")
@XmlSeeAlso({ org.oasis_open.docs.ns.cmis.core._200908.ObjectFactory.class,
		org.oasis_open.docs.ns.cmis.messaging._200908.ObjectFactory.class })
public interface RepositoryServicePort {

	@WebResult(name = "types", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
	@RequestWrapper(localName = "getTypeChildren", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.GetTypeChildren")
	@WebMethod(action = "getTypeChildren")
	@ResponseWrapper(localName = "getTypeChildrenResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.GetTypeChildrenResponse")
	public org.oasis_open.docs.ns.cmis.messaging._200908.CmisTypeDefinitionListType getTypeChildren(
			@WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String repositoryId,
			@WebParam(name = "typeId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String typeId,
			@WebParam(name = "includePropertyDefinitions", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.Boolean includePropertyDefinitions,
			@WebParam(name = "maxItems", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.math.BigInteger maxItems,
			@WebParam(name = "skipCount", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.math.BigInteger skipCount,
			@WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException;

	@WebResult(name = "type", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
	@RequestWrapper(localName = "getTypeDefinition", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.GetTypeDefinition")
	@WebMethod(action = "getTypeDefinition")
	@ResponseWrapper(localName = "getTypeDefinitionResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.GetTypeDefinitionResponse")
	public org.oasis_open.docs.ns.cmis.core._200908.CmisTypeDefinitionType getTypeDefinition(
			@WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String repositoryId,
			@WebParam(name = "typeId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String typeId,
			@WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException;

	@RequestWrapper(localName = "updateType", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.UpdateType")
	@WebMethod(action = "updateType")
	@ResponseWrapper(localName = "updateTypeResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.UpdateTypeResponse")
	public void updateType(
			@WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String repositoryId,
			@WebParam(mode = WebParam.Mode.INOUT, name = "type", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") javax.xml.ws.Holder<org.oasis_open.docs.ns.cmis.core._200908.CmisTypeDefinitionType> type,
			@WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException;

	@WebResult(name = "repositoryInfo", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
	@RequestWrapper(localName = "getRepositoryInfo", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.GetRepositoryInfo")
	@WebMethod(action = "getRepositoryInfo")
	@ResponseWrapper(localName = "getRepositoryInfoResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.GetRepositoryInfoResponse")
	public org.oasis_open.docs.ns.cmis.core._200908.CmisRepositoryInfoType getRepositoryInfo(
			@WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String repositoryId,
			@WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException;

	@RequestWrapper(localName = "deleteType", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.DeleteType")
	@WebMethod(action = "deleteType")
	@ResponseWrapper(localName = "deleteTypeResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.DeleteTypeResponse")
	public void deleteType(
			@WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String repositoryId,
			@WebParam(name = "typeId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String typeId,
			@WebParam(mode = WebParam.Mode.INOUT, name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") javax.xml.ws.Holder<org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType> extension)
			throws CmisException;

	@WebResult(name = "types", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
	@RequestWrapper(localName = "getTypeDescendants", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.GetTypeDescendants")
	@WebMethod(action = "getTypeDescendants")
	@ResponseWrapper(localName = "getTypeDescendantsResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.GetTypeDescendantsResponse")
	public java.util.List<org.oasis_open.docs.ns.cmis.messaging._200908.CmisTypeContainer> getTypeDescendants(
			@WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String repositoryId,
			@WebParam(name = "typeId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String typeId,
			@WebParam(name = "depth", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.math.BigInteger depth,
			@WebParam(name = "includePropertyDefinitions", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.Boolean includePropertyDefinitions,
			@WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException;

	@RequestWrapper(localName = "createType", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.CreateType")
	@WebMethod(action = "createType")
	@ResponseWrapper(localName = "createTypeResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.CreateTypeResponse")
	public void createType(
			@WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") java.lang.String repositoryId,
			@WebParam(mode = WebParam.Mode.INOUT, name = "type", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") javax.xml.ws.Holder<org.oasis_open.docs.ns.cmis.core._200908.CmisTypeDefinitionType> type,
			@WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException;

	@WebResult(name = "repositories", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
	@RequestWrapper(localName = "getRepositories", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.GetRepositories")
	@WebMethod(action = "getRepositories")
	@ResponseWrapper(localName = "getRepositoriesResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "org.oasis_open.docs.ns.cmis.messaging._200908.GetRepositoriesResponse")
	public java.util.List<org.oasis_open.docs.ns.cmis.messaging._200908.CmisRepositoryEntryType> getRepositories(
			@WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/") org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType extension)
			throws CmisException;
}
